name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_publish:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4.1.4
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install requirements with PDF
        run: pip install -r requirements.txt -r pdf_requirements.txt
      - name: Inject plugin
        run: bin/inject_pdf.sh

      - name: Deploy docs
        run: mkdocs gh-deploy --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

